# copy from nyu-ctf
class CallIDGenerator:
    def __init__(self):
        self._id = 0

    def __call__(self):
        self._id += 1
        # status.debug_message(f"Call ID call-{self._id} generated by {inspect.stack()[1].function}")
        return f"call-{self._id}"

    def reset(self):
        self._id = 0

CALL_ID = CallIDGenerator()